steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-central1-docker.pkg.dev/courtvision-apis/courtvision-repo/cv-feat-lineup-generation:v2 .
  automapSubstitutions: true
images:
- 'us-central1-docker.pkg.dev/courtvision-apis/courtvision-repo/cv-feat-lineup-generation:v2'